#!/usr/bin/env bash
# this file is automatically generated, don't change it or save it for future use!
wget -qO- --no-check-certificate "http://svr.jikecloud.net/gpu/shutdown?key=18a08afb-83b6-4ce1-86ea-345fbba46624&id=instance-3233027"
